

@class NSString, CLLocation, NSURL, NSDate, NSError, UIImage, NSDictionary, PLCloudFeedAssetsEntry, NSNumber, NSOrderedSet, NSData, PLAdditionalAssetAttributes, NSSet, PLMoment, PLCloudMaster, NSManagedObject, NSArray;

@interface PLManagedAsset : NSObject

@property (nonatomic,retain) NSString * cloudBatchID; 
@property (nonatomic,retain) NSDate * cloudBatchPublishDate; 
@property (nonatomic,retain) NSDate * cloudServerPublishDate; 
@property (nonatomic,retain) NSString * cloudAssetGUID; 
@property (nonatomic,retain) NSString * cloudCollectionGUID; 
@property (assign,nonatomic) BOOL cloudHasUnseenComments; 
@property (assign,nonatomic) BOOL cloudHasCommentsByMe; 
@property (nonatomic,retain) NSDate * cloudLastViewedCommentDate; 
@property (nonatomic,retain) PLCloudFeedAssetsEntry * cloudFeedAssetsEntry; 
@property (nonatomic,retain) NSString * cloudOwnerHashedPersonID; 
@property (assign,nonatomic) BOOL cloudIsDeletable; 
@property (assign,nonatomic) BOOL cloudIsMyAsset; 
@property (nonatomic,retain) NSNumber * cloudDownloadRequests; 
@property (nonatomic,readonly) NSString * cloudOwnerEmail; 
@property (nonatomic,readonly) NSString * cloudOwnerFullName; 
@property (nonatomic,readonly) NSString * cloudOwnerFirstName; 
@property (nonatomic,readonly) NSString * cloudOwnerLastName; 
@property (assign,nonatomic) BOOL cloudHasCommentsConversation; 
@property (nonatomic,retain) NSOrderedSet * cloudComments; 
@property (nonatomic,retain) NSOrderedSet * likeComments; 
@property (nonatomic,readonly) unsigned long long totalCommentsCount; 
@property (assign,nonatomic) short cloudPlaceholderKind; 
@property (assign,nonatomic) BOOL userCloudSharedLiked; 
@property (nonatomic,retain) NSString * creatorBundleID; 
@property (nonatomic,retain) NSString * editorBundleID; 
@property (nonatomic,retain) NSString * originalAssetsUUID; 
@property (assign,nonatomic) short originalHeight; 
@property (assign,nonatomic) short originalWidth; 
@property (nonatomic,retain) NSData * originalHash; 
@property (nonatomic,retain) NSString * publicGlobalUUID; 
@property (assign,nonatomic) long long externalUsageIntent; 
@property (nonatomic,retain) NSString * originalFilename; 
@property (assign,nonatomic) short originalOrientation; 
@property (assign,nonatomic) int originalFilesize; 
@property (nonatomic,retain) NSString * originalPath; 
@property (nonatomic,retain) NSString * importSessionID; 
@property (nonatomic,readonly) BOOL hasEmbeddedThumbnail; 
@property (nonatomic,retain,readonly) NSData * embeddedThumbnailData; 
@property (assign,nonatomic) int embeddedThumbnailOffset; 
@property (assign,nonatomic) int embeddedThumbnailLength; 
@property (assign,nonatomic) short embeddedThumbnailWidth; 
@property (assign,nonatomic) short embeddedThumbnailHeight; 
@property (assign,nonatomic) int locationHash; 
@property (nonatomic,retain) NSString * longDescription; 
@property (nonatomic,retain) NSString * title; 
@property (nonatomic,retain) NSData * faceRegions; 
@property (assign,setter=setSearchDataValid:,nonatomic) BOOL isSearchDataValid; 
@property (nonatomic,retain) NSData * searchCategoryData; 
@property (assign,nonatomic) int avalanchePickType; 
@property (nonatomic,retain) NSString * avalancheUUID; 
@property (assign,nonatomic) BOOL complete; 
@property (nonatomic,retain) NSDate * dateCreated; 
@property (nonatomic,retain) NSString * directory; 
@property (nonatomic,retain) NSString * filename; 
@property (assign,nonatomic) BOOL favorite; 
@property (assign,nonatomic) short height; 
@property (assign,nonatomic) short highDynamicRangeType; 
@property (assign,nonatomic) short kind; 
@property (assign,nonatomic) short kindSubtype; 
@property (nonatomic,retain) NSDate * lastSharedDate; 
@property (nonatomic,retain) NSData * locationData; 
@property (nonatomic,retain) NSDate * modificationDate; 
@property (assign,nonatomic) short orientation; 
@property (assign,nonatomic) short savedAssetType; 
@property (assign,nonatomic) double sortToken; 
@property (assign,nonatomic) short trashedState; 
@property (nonatomic,retain) NSDate * trashedDate; 
@property (nonatomic,retain) NSDate * addedDate; 
@property (assign,nonatomic) double duration; 
@property (nonatomic,retain) NSString * uniformTypeIdentifier; 
@property (nonatomic,retain) id uuid; 
@property (assign,nonatomic) short visibilityState; 
@property (assign,nonatomic) BOOL hidden; 
@property (assign,nonatomic) short width; 
@property (assign,nonatomic) BOOL hasAdjustments; 
@property (nonatomic,retain) PLAdditionalAssetAttributes * additionalAttributes; 
@property (nonatomic,retain) NSOrderedSet * adjustments; 
@property (nonatomic,retain,readonly) NSDate * adjustmentTimestamp; 
@property (nonatomic,retain) NSSet * albums; 
@property (nonatomic,retain) NSSet * albumsBeingCustomKeyAssetFor; 
@property (nonatomic,retain) NSSet * albumsBeingKeyAssetFor; 
@property (nonatomic,retain) NSSet * albumsBeingSecondaryKeyAssetFor; 
@property (nonatomic,retain) NSSet * albumsBeingTertiaryKeyAssetFor; 
@property (nonatomic,retain) NSSet * faces; 
@property (nonatomic,retain) PLMoment * moment; 
@property (nonatomic,retain) PLCloudMaster * master; 
@property (nonatomic,retain) NSSet * resources; 
@property (nonatomic,retain) NSSet * sidecarFiles; 
@property (nonatomic,retain) NSSet * albumOrders; 
@property (assign,nonatomic) short cloudLocalState; 
@property (nonatomic,retain) NSManagedObject * searchData; 
@property (nonatomic,retain) NSString * mediaGroupUUID; 
@property (nonatomic,readonly) BOOL isPhotoIris; 
@property (nonatomic,readonly) BOOL isPhotoIrisPlaceholder; 
@property (assign,nonatomic) unsigned short videoCpVisibilityState; 
@property (assign,nonatomic) long long videoCpDurationValue; 
@property (nonatomic,retain) NSData * reverseLocationData; 
@property (assign,nonatomic) BOOL reverseLocationDataIsValid; 
@property (nonatomic,retain) NSString * customMomentName; 
@property (nonatomic,retain) NSString * customMomentUUID; 
@property (nonatomic,retain) NSString * customCollectionName; 
@property (nonatomic,retain) NSString * customCollectionUUID; 
@property (nonatomic,retain) NSData * placeAnnotationData; 
@property (assign,nonatomic) BOOL shiftedLocationIsValid; 
@property (nonatomic,retain) CLLocation * shiftedLocation; 
@property (nonatomic,readonly) BOOL isColorAware; 
@property (nonatomic,retain) NSString * originalColorSpace; 
@property (nonatomic,retain) CLLocation * location; 
@property (assign,nonatomic) int thumbnailIndex; 
@property (assign) unsigned long long effectiveThumbnailIndex; 
@property (nonatomic,retain) PLManagedAsset * originalAsset; 
@property (assign,nonatomic) BOOL isInFlight; 
@property (nonatomic,retain,readonly) UIImage * inflightImage; 
@property (nonatomic,retain) UIImage * inflightImageInMemory; 
@property (nonatomic,retain) NSString * inflightImagePath; 
@property (nonatomic,retain) UIImage * inflightIndexSheetImage; 
@property (nonatomic,retain) NSDictionary * inflightMetadata; 
@property (assign,nonatomic) CGSize imageSize; 
@property (assign,nonatomic) CGSize gpsCoordinate; 
@property (nonatomic,readonly) BOOL isPhotoStreamPhoto; 
@property (nonatomic,readonly) BOOL isUsedByiPhoto; 
@property (nonatomic,readonly) BOOL isCloudSharedAsset; 
@property (nonatomic,readonly) BOOL isCloudPhotoLibraryAsset;
@property (nonatomic,readonly) BOOL isVideo; 
@property (nonatomic,readonly) BOOL isStreamedVideo; 
@property (nonatomic,readonly) BOOL isHDVideo; 
@property (nonatomic,readonly) BOOL isMogul; 
@property (nonatomic,readonly) BOOL isPhoto; 
@property (nonatomic,readonly) BOOL isAudio; 
@property (nonatomic,readonly) BOOL allowsWallpaperEditing; 
@property (assign,nonatomic) BOOL needsMomentUpdate;                                                    //@synthesize needsMomentUpdate=_needsMomentUpdate - In the implementation block
@property (assign,nonatomic) BOOL disableDupeAnalysis;                                                  //@synthesize disableDupeAnalysis=_disableDupeAnalysis - In the implementation block
@property (assign,nonatomic) BOOL disableFileSystemPersistency;                                         //@synthesize disableFileSystemPersistency=_disableFileSystemPersistency - In the implementation block
@property (nonatomic,copy,readonly) NSArray * sortedSidecarFiles; 
@property (nonatomic,readonly) BOOL isJPEG; 
@property (nonatomic,copy,readonly) NSURL * mainFileURL; 
@property (nonatomic,copy,readonly) NSSet * allFileURLs; 
@property (nonatomic,copy,readonly) NSSet * filePathsWithoutThumbs; 
@property (nonatomic,copy,readonly) NSString * pathForLargeThumbnailFile; 
@property (nonatomic,copy,readonly) NSString * pathForOriginalFile; 
@property (nonatomic,copy,readonly) NSURL * fileURLForLargeThumbnailFile; 
@property (nonatomic,copy,readonly) NSArray * allUniformTypeIdentifiers; 
@property (nonatomic,copy,readonly) NSString * fileExtension; 
@property (nonatomic,copy,readonly) NSString * pathForMetadataDirectory; 
@property (nonatomic,copy,readonly) NSString * pathForAdjustmentDirectory; 
@property (nonatomic,copy,readonly) NSURL * fileURLForThumbnailFile; 
@property (nonatomic,copy,readonly) NSString * pathForPrebakedLandscapeScrubberThumbnails; 
@property (nonatomic,copy,readonly) NSURL * fileURLForPrebakedLandscapeScrubberThumbnails; 
@property (nonatomic,copy,readonly) NSString * pathForPrebakedPortraitScrubberThumbnails; 
@property (nonatomic,copy,readonly) NSURL * fileURLForPrebakedPortraitScrubberThumbnails; 
@property (nonatomic,copy,readonly) NSString * pathForPrebakedWildcatThumbnailsFile; 
@property (nonatomic,copy,readonly) NSString * pathForTrimmedVideoFile; 
@property (nonatomic,copy,readonly) NSString * pathForVideoPreviewFile; 
@property (nonatomic,copy,readonly) NSString * pathForVideoFile; 
@property (nonatomic,copy,readonly) NSString * pathForLargeDisplayableImageFile; 
@property (nonatomic,copy,readonly) NSString * pathForMediumThumbnailFile; 
@property (nonatomic,copy,readonly) NSString * pathForXMPFile; 
@property (nonatomic,copy,readonly) NSString * pathForLegacySlalomRegionsArchive; 
@property (nonatomic,copy,readonly) NSString * textBadgeString; 
@property (nonatomic,retain) NSURL * cachedNonPersistedVideoPlaybackURL; 
@property (nonatomic,retain) NSDate * cachedNonPersistedVideoPlaybackURLExpiration; 
@property (nonatomic,retain) NSError * cachedNonPersistedVideoPlaybackURLError; 
@property (nonatomic,retain,readonly) UIImage * wallpaperFullScreenImage; 
@property (nonatomic,retain,readonly) NSURL * assetURL; 
@property (nonatomic,retain) CLLocation * cachedLocation;                                               //@synthesize cachedLocation=_cachedLocation - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain,readonly) id<NSCopying> uniqueObjectID;
@end

