@class NSMutableArray, PLGenericAlbum, NSCalendar, NSMutableDictionary, NSSet, PLManagedAlbum, PLFetchingAlbum, PLInFlightAssetsAlbum, PLManagedAlbumList, PLManagedFolder, NSString, PLManagedObjectContext, NSArray;
@protocol PLAlbumProtocol;

@interface PLPhotoLibrary : NSObject

@property (nonatomic,retain) PLManagedObjectContext * managedObjectContext; 
@property (nonatomic,retain,readonly) id<PLAlbumProtocol> savedPhotosAlbum; 
@property (nonatomic,retain,readonly) id<PLAlbumProtocol> userLibraryAlbum; 
@property (nonatomic,retain,readonly) id<PLAlbumProtocol> inFlightAssetsAlbum; 
@property (nonatomic,retain,readonly) PLManagedAlbumList * rootAlbumList; 
@property (nonatomic,retain,readonly) PLManagedFolder * rootFolder; 
@property (nonatomic,copy,readonly) NSArray * albums; 
@property (nonatomic,copy,readonly) NSArray * userAlbums; 
@property (nonatomic,copy,readonly) NSArray * imagePickerAlbums; 
@property (nonatomic,copy,readonly) NSArray * wallpaperAlbums; 
@property (nonatomic,copy,readonly) NSArray * importAlbums; 
@property (nonatomic,copy,readonly) NSArray * eventAlbums; 
@property (nonatomic,copy,readonly) NSArray * faceAlbums; 
@property (nonatomic,copy,readonly) NSArray * placeAlbums; 
@property (nonatomic,copy,readonly) id<PLAlbumProtocol> favoritesAlbum; 
@property (nonatomic,copy,readonly) NSArray * photoStreamAlbums; 
@property (nonatomic,copy,readonly) NSArray * photoStreamAlbumsForPreferences; 

+(void)performTransactionAndWaitOnTransientLibraryWithName:(const char*)arg1 block:(/*^block*/id)arg2 ;
+(id)_operationQueueForPriority:(long long)arg1 ;
+(id)_statusDescriptionForQueue:(id)arg1 ;
+(id)queueStatusDescription;
+(void)performOnTransientLibraryWithPriority:(long long)arg1 name:(const char*)arg2 block:(/*^block*/id)arg3 completionHandler:(/*^block*/id)arg4 ;
+(BOOL)_assetsdQueueingMode;
+(void)_enqueueOperationWithName:(id)arg1 priority:(long long)arg2 block:(/*^block*/id)arg3 ;
+(void)_activateStatusTimer;
+(void)performOnTransientLibraryWithPriority:(long long)arg1 name:(const char*)arg2 block:(/*^block*/id)arg3 ;
+(void)performAndWaitOnTransientLibraryWithName:(const char*)arg1 block:(/*^block*/id)arg2 ;
+(BOOL)isRunningInStoreDemoMode;
+(unsigned long long)sharedStreamsSize;
+(id)lightweightReimportPhotoCloudSharingDataDirectory;
+(id)photoCloudSharingCacheDataDirectory;
+(id)photoMetadataDirectoryURL;
+(id)fileReservationForFileAtPath:(id)arg1 exclusive:(BOOL)arg2 ;
+(void)setSqliteErrorAndExitIfNecessary;
+(id)crashRecoveryIndicatorFilePaths:(BOOL)arg1 ;
+(void)_enqeueRecoveryJob:(id)arg1 ;
+(id)opportunisticTaskIsolationQueue;
+(BOOL)photoLibraryIsObtainable;
+(id)photoDataDirectory;
+(void)setApplicationIsWildcat:(BOOL)arg1 ;
+(void)_doFilesystemImportIfNeededWithMOC:(id)arg1 reason:(id)arg2 ;
+(id)photoCloudSharingDataDirectory;
+(id)photoDataCachesDirectory;
+(id)dcimDirectoryURL;
+(void)_inq_createPhotoStreamAlbumStreamID:(id)arg1 inLibrary:(id)arg2 ;
+(id)takingVideoIndicatorFilePath;
+(id)takingPhotoIndicatorFilePath;
+(id)imageWriterIndicatorFilePath;
+(BOOL)libraryAvailableIndicatorState;
+(id)pathToAssetsToAlbumsMapping;
+(id)iTunesSyncedAssetsDirectory;
+(id)mediaFilesDirectoryURL;
+(id)persistedAlbumDataDirectoryURL;
+(void)setLibraryAvailableIndicatorState:(BOOL)arg1 ;
+(void)postGlobalPhotoLibraryAvailableNotification;
+(void)repairSingletonObjects;
+(id)migrationIndicatorFilePath;
+(id)momentAnalysisNeededFilePath;
+(id)forceSoftResetSyncPath;
+(id)disableICloudPhotosFilePath;
+(id)enableICloudPhotosFilePath;
+(void)updateICloudPhotosMarkerForEnable:(BOOL)arg1 ;
+(void)setCameraRollCountedInQuota:(BOOL)arg1 ;
+(BOOL)isICloudPhotosPaused;
+(void)setPauseMarker:(BOOL)arg1 ;
+(BOOL)isEnableICloudPhotos;
+(BOOL)isDisableICloudPhotos;
+(BOOL)isForceSoftResetSync;
+(id)cplEnableMarkerFilePath;
+(id)cplDownloadFinishedMarkerFilePath;
+(id)pauseICloudPhotosFilePath;
+(id)dupeAnalysisNeededFilePath;
+(id)libraryAvailableIndicatorFilePath;
+(id)streamsLibraryUpdatingExpiredIndicatorFilePath;
+(id)_dataProtectionIndicatorFilePath;
+(id)_dataMigratorFinishedFilePath;
+(id)photoDataDirectoryURL;
+(id)photoDataCPLDirectory;
+(BOOL)processWithID:(int)arg1 canReadSandboxForPath:(id)arg2 ;
+(BOOL)processWithID:(int)arg1 canWriteSandboxForPath:(id)arg2 ;
+(id)sqliteErrorIndicatorFilePath;
+(BOOL)createSqliteErrorIndicatorFile;
+(id)iTunesSyncedFaceAlbumThumbnailsDirectory;
+(id)iTunesSyncedFaceDataDirectory;
+(id)iTunesPhotosDirectory;
+(id)iTunesSyncedAssetMetadataThumbnailsDirectory;
+(id)iTunesSyncedAssetSmallThumbnailsDirectory;
+(void)resetSyncedAssetsDCIMDirectory;
+(id)photoMetadataDirectoryURLForMediaInMainDirectory:(id)arg1 ;
+(id)photoMutationsDirectory;
+(id)photoStreamsDataDirectory;
+(BOOL)isDupeAnalysisNeeded;
+(BOOL)isDataMigratorFinished;
+(void)setDataMigratorFinished:(BOOL)arg1 ;
+(id)syncInfoPath;
+(void)refreshCachedCountsOnAssetsContainerClass:(Class)arg1 inContext:(id)arg2 withPredicate:(id)arg3 ;
+(BOOL)isApplicationWildcat;
+(void)handlePossibleCoreDataError:(id)arg1 ;
+(void)recoverFromCrashIfNeeded;
+(void)disableOpportunisticTasks:(BOOL)arg1 ;
+(BOOL)areOpportunisticTasksDisabled;
+(BOOL)isSafeToRecoverAfterCrash;
+(void)setPhotoStreamEnabled:(BOOL)arg1 ;
+(void)setCloudAlbumSharingEnabled:(BOOL)arg1 ;
+(id)photoCloudSharingMetadataDirectory;
+(id)lightweightReimportPhotoCloudSharingAssetDirectoryForAlbumWithCloudGUID:(id)arg1 cloudPersonID:(id)arg2 ;
+(id)lightweightReimportPhotoCloudSharingAssetFileNameWithCloudAssetGUID:(id)arg1 type:(id)arg2 ;
+(id)assetsDataDirectory;
+(void)createPhotoStreamAlbumWithStreamID:(id)arg1 inLibrary:(id)arg2 ;
+(void)createPhotoStreamAlbumWithStreamID:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
+(void)setMigratorIsBusy:(BOOL)arg1 ;
+(void)setImageWriterIsBusy:(BOOL)arg1 ;
+(void)setVideoCaptureIsBusy:(BOOL)arg1 ;
+(void)setTakingPhotoIsBusy:(BOOL)arg1 ;
+(void)setMomentAnalysisNeeded:(BOOL)arg1 ;
+(BOOL)isMomentAnalysisNeeded;
+(void)forceSoftResetSync;
+(void)setDisableICloudPhotos:(BOOL)arg1 ;
+(void)setEnableICloudPhotos:(BOOL)arg1 ;
+(void)setICloudPhotosEnabled:(BOOL)arg1 ;
+(id)pauseTime;
+(void)setDupeAnalysisNeeded:(BOOL)arg1 ;
+(void)setDataProtectionComplete:(BOOL)arg1 ;
+(BOOL)isDataProtectionComplete;
+(id)videosPath;
+(id)photoDataCPLDerivativeDirectory;
+(id)photoDataCPLLibraryIdentifier;
+(id)photoDataCPLResourceDestinationDirectoryWithIdentifier:(id)arg1 ;
+(id)cplAssetsDirectoryURL;
+(id)dcimDirectory;
+(id)simpleDCIMDirectory;
+(BOOL)processCanReadSandboxForPath:(id)arg1 ;
+(BOOL)processCanWriteSandboxForPath:(id)arg1 ;
+(void)initializeGraphicsServices;
+(BOOL)canSaveVideoToCameraRoll:(id)arg1 ;
+(BOOL)isAlbumSynced:(id)arg1 ;
+(void)delayedRefreshCachedCountsInAlbumIDs:(id)arg1 ;
+(void)updateAlbumKeyAssetsInContext:(id)arg1 withPredicate:(id)arg2 ;
+(void)_assetsLibrary_disableSharedPhotoStreamsSupport;
+(BOOL)_assetsLibrary_isSharedPhotoStreamsSupportEnabled;
+(unsigned long long)CloudPhotoLibrarySize;
+(id)sharedPhotoLibrary;
+(id)photoDataMiscDirectory;
+(id)savedPhotosAlbum;
+(id)photoOutboundSharingTmpDirectoryURL;
+(BOOL)isStreamsLibraryUpdatingExpired;
+(void)setStreamsLibraryUpdatingExpired:(BOOL)arg1 ;
+(id)syncedAlbumSubtitleStringFormat;
@end

